[package]
name = "offset-bin"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
license = "AGPL-3.0"
edition = "2018"

[lib]
name = "bin"
path = "src/lib.rs"

[[bin]]
name = "strelay"
path = "src/bin/strelay.rs"

[[bin]]
name = "stindex"
path = "src/bin/stindex.rs"

[[bin]]
name = "stnode"
path = "src/bin/stnode.rs"

[[bin]]
name = "stmgr"
path = "src/bin/stmgr.rs"

[dependencies]

common = { path = "../common", version = "0.1.0", package = "offset-common" }
crypto = { path = "../crypto", version = "0.1.0", package = "offset-crypto" }
identity = { path = "../identity", version = "0.1.0" , package = "offset-identity" }
timer = { path = "../timer", version = "0.1.0" , package = "offset-timer" }
proto = { path = "../proto", version = "0.1.0" , package = "offset-proto" }
relay = { path = "../relay", version = "0.1.0" , package = "offset-relay" }
net = { path = "../net", version = "0.1.0" , package = "offset-net" }
index_server = { path = "../index_server", version = "0.1.0" , package = "offset-index-server" }
node = { path = "../node", version = "0.1.0" , package = "offset-node" }
database = { path = "../database", version = "0.1.0" , package = "offset-database" }
connection = { path = "../connection", version = "0.1.0" , package = "offset-connection" }

serde = {version = "1.0.104", features = ["derive"]}
base64 = "0.10.1"

log = "0.4"
env_logger = "0.6.0"
futures = {version = "0.3.1", features = ["thread-pool"]}
async-std = "1.6.2"

structopt = "0.2.15"

derive_more = "0.99.2"

[dev-dependencies]

tempfile = "3.1.0"
